### PR TITLE
Fix Trello#74, chickens not landing properly.

### PR DESCRIPTION
**Pull request by AricStewart**
Also general chicken movement improvements

### CODE REVIEW

**Comment by yelworc** [comment]
Couldn't we simply supply `onPlatformLanding` as the callback in `apiKickTheChicken`? Or are you planning to add more functionality to `Item.prototype.kickCallback` (the TODO seems to suggest that, but I'm not sure what the "more" would be)?

**Comment by AricStewart** [comment]
There are 2 possibilities, onPlatformLanding and onLadderLanding. Only onPlatformLanding is used right now as I have paid no attention to ladders at all.

It is stil possible we could just use that as the callback itself, the only worry was with the face thatt he onXLanding functions take no arguments and the status callbacks get arguments. Not sure if that is an issue with JavaScript or not.

**Comment by yelworc** [comment]
Ah right, ladders. No, calling the `on*Landing` functions with (unused) arguments should not be a problem.

Maybe I'm overthinking this, but having the type-specific function `kickCallback` in the generic `Item` class seems wrong to me. What do you think about not supplying the callback in `apiKickTheChicken` at all, but instead setting it to `onPlatformLanding` (or later optionally `onLadderLanding`) in `ItemMovement.buildPath` (for the transport mode `kicked`)?

**Comment by AricStewart** [comment]
Nope sounds good. I would also greatly prefer to not have that dangling little callback and if the extra parameters are not a problem then we can just add the callback when building the path. I will do that and resend.

**Pull request closed without merging**
