### PR TITLE
Instancing and Housing

### PR DESCRIPTION
**Pull request by KaiyonAlatar**
Changes needed for both instancing and housing.

Needs merge/pull requests completed in eleven-gsjs and eleven-fixtures (private repo) as well.

### CODE REVIEW

**Comment by KaiyonAlatar** [comment]
Just noticed a few things that can be removed still.  I'll do that tomorrow.  There are still going to be some things that don't work in the housing, and this is mainly just related to the creation of them.  I'll create further pull requests as I fix more issues.

**Comment by Mexiswow** [comment]
How can I get access to the eleven-fixtures?
I can JS, HTML, PHP, SQL, CSS.

Well versed in the code and quickly learn. I will gladly help.
I have experience with Pythton, Delphi, C #

**Comment by KaiyonAlatar** [comment]
Send an email to slack@elevengiants.com with your skills.

**Comment by Mexiswow** [comment]
KaiyonAlatar, i sent, thank you ))

**Pull request closed without merging**
